#pragma config(Sensor, S1,     HTMC,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "\Programs\RampRiot\utils\compassStorage.h"
#include "drivers/hitechnic-compass.h"

task main () {
	int total = 0;
	int count = 0;

	while (count <= 5) {
		// Get the true heading and relative heading from the sensor and
		// display them on the screen.
		while(nNxtButtonPressed != kEnterButton) {
			eraseDisplay();
			nxtDisplayCenteredBigTextLine(0, "Reading");
			nxtDisplayTextLine(2, "Target Avg: %4d", total / count);
			nxtDisplayTextLine(3, "Abs:   %4d", HTMCreadHeading(HTMC));
			nxtDisplayCenteredTextLine(6, "Press enter");
			nxtDisplayCenteredTextLine(7, "to set target");
			wait1Msec(100);
		}

		// Reset the target no more than once a second
		// This also helps with debouncing the [enter] button.
		eraseDisplay();
		nxtDisplayTextLine(1, "Changing");
		nxtDisplayTextLine(2, "target");
		wait1Msec(500);
		// Set the current heading as the value for the offset to be used as the
		// new zero-point for the relative heading returned by
		// HTMCreadRelativeHeading()
		count++;
		total += HTMCreadHeading(HTMC);
		PlaySound(soundBlip);
		while(bSoundActive) break;
	}
}
